import { port } from "./_helpers";
import type { DeviceTemplate } from "../types";

/**
 * DWAV-verified device templates, compiled from the CRM Device Ports subform.
 * Ship this file via a normal push+deploy so every DWAV EasySchematic user gets
 * these automatically -- no manual "Import from JSON" step, no localStorage
 * dependency. Each device's `id` should be treated as stable: it round-trips
 * back to the CRM product's compiled template.
 *
 * Do not edit by hand for anything CRM-managed -- regenerate from CRM via the
 * Design Studio compiler once it exists. See dwav-design-studio/docs/CREATED.md.
 */
export const templates: DeviceTemplate[] = [
  {
    id: "37e3b485-ed14-4d44-83d7-703cc6b6df3f",
    dwavVerified: true,
    deviceType: "wired-mic",
    label: "Audio-Technica BP3600",
    manufacturer: "Audio-Technica",
    modelNumber: "BP3600",
    referenceUrl: "https://www.audio-technica.com/en-us/bp3600",
    searchTerms: ["bp3600", "immersive audio", "microphone array", "8-channel", "atmos mic", "dwav"],
    unitCost: 8472,   // MSRP — DWAV rule: never dealer cost in this public file
    ports: [
      {
        ...port("Audio Out (8-ch)", "analog-audio", "output", "multipin"),
        channelCount: 8,
        notes:
          "LEMO 2B 10-pin multi-out on mic body. Ships with LEMO-to-XLRM (x8) breakout cable for 8 discrete channels; each channel requires 48V phantom from the downstream device.",
      },
    ],
  },
  {
    id: "7af08446-b1a9-49ef-a0b7-88b6d789be31",
    dwavVerified: true,
    deviceType: "wired-mic",
    label: "Audio-Technica ATND1061DAN",
    manufacturer: "Audio-Technica",
    modelNumber: "ATND1061DAN",
    referenceUrl: "https://www.audio-technica.com/en-us/atnd1061",
    searchTerms: ["atnd1061", "beamforming", "ceiling array", "dante", "poe", "dwav"],
    widthMm: 227.5,
    depthMm: 227.5,
    heightMm: 30,
    weightKg: 1.25,
    unitCost: 4844,
    ports: [
      {
        ...port("Dante Primary", "dante", "bidirectional", "rj45"),
        addressable: true,
        poeDrawW: 7,
        notes:
          "Carries Dante audio + mic control data (100 Mbps control over 1 Gbps link). PoE input, IEEE 802.3af Class 0, 7W max.",
      },
      {
        ...port("Dante Secondary", "dante", "bidirectional", "rj45"),
        addressable: true,
        notes: "Redundant Dante network port (Single Cable or Split mode).",
      },
      {
        ...port("Analog Input", "analog-audio", "input", "phoenix"),
        notes: "Euroblock 3-pin. External analog mic/source input.",
      },
      {
        ...port("Analog Output", "analog-audio", "output", "phoenix"),
        notes: "Euroblock 3-pin. Local analog output for non-Dante integration.",
      },
      {
        ...port("GPI", "contact-closure", "input", "phoenix"),
        notes: "Euroblock 3-pin general-purpose trigger input.",
      },
    ],
  },
  {
    id: "46f26a4d-ce40-4f16-b042-a4e34c1c4d36",
    dwavVerified: true,
    deviceType: "speaker",
    label: "Martin Audio ACS-40TS-W",
    manufacturer: "Martin Audio",
    modelNumber: "ACS-40TS-W",
    referenceUrl: "https://martin-audio.com/products/loudspeakers/acs-40ts",
    searchTerms: ["acs-40ts", "adorn", "ceiling speaker", "70v", "100v", "dwav"],
    widthMm: 221,
    depthMm: 115,
    heightMm: 30,
    weightKg: 2.2,
    unitCost: 135,
    ports: [
      {
        ...port("Audio In", "speaker-level", "input", "terminal-block"),
        notes:
          "Ceramic terminal block, positions 1&2 (+/-). 70V taps: 20/10/5/2.5W; 100V taps: 20/10/5W; 16-ohm direct also selectable.",
      },
      {
        ...port("Link Out", "speaker-level", "output", "terminal-block"),
        notes: "Ceramic terminal block, positions 3&4 (+/-). Loop-through to next speaker in a daisy chain.",
      },
    ],
  },
  {
    id: "1f4c9a2e-6b3d-4e57-8a10-2c9e7d5b4a01",
    deviceType: "display",
    label: "Samsung QM32C",
    shortName: "QM32C",
    manufacturer: "Samsung",
    modelNumber: "QM32C",
    referenceUrl: "https://images.samsung.com/is/content/samsung/assets/de/business/displays/pdf/Datenblatt_Smart-Signage_LH32QMCEBGCXEN.pdf",
    searchTerms: ["qm32c", "qmc", "samsung signage", "32 inch", "commercial display", "tizen", "dwav"],
    widthMm: 727.3,
    heightMm: 421.9,
    depthMm: 28.5,
    weightKg: 5.2,
    powerDrawW: 29,
    voltage: "100-240V",
    unitCost: 840,
    dwavVerified: true,
    // 32" Full HD QMC-series commercial display, VESA 100x100 M4. Verified 2026-09-11 against Samsung's own
    // spec sheets (see referenceUrl); CRM Products record carries the same ports + ES_Template_ID.
    ports: [
      { ...port("HDMI In 1", "hdmi", "input", "hdmi"), notes: "HDMI (HDCP 2.2)" },
      { ...port("HDMI In 2", "hdmi", "input", "hdmi"), notes: "HDMI (HDCP 2.2)" },
      { ...port("HDMI In 3", "hdmi", "input", "hdmi"), notes: "HDMI (HDCP 2.2)" },
      { ...port("USB 1", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port: media playback, firmware, peripherals." },
      { ...port("USB 2", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port." },
      { ...port("Audio Out", "analog-audio", "output", "trs-eighth"), notes: "Stereo mini-jack line out. No analog audio input on this series." },
      { ...port("RS232C In", "serial", "input", "trs-eighth"), notes: "RS-232C on a 3.5 mm stereo jack; Samsung ships an RS232C (IN) gender adapter to DB9 in the box." },
      { ...port("RS232C Out", "serial", "output", "trs-eighth"), notes: "RS-232C loop-through to the next display (3.5 mm stereo jack)." },
      { ...port("LAN", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "RJ45 for MagicINFO/SSSP, MDC control and firmware." },
      { ...port("Wi-Fi", "ethernet", "bidirectional", "wireless"), addressable: true, notes: "Built-in Wi-Fi 2.4/5 GHz dual band." },
      { ...port("Bluetooth", "bluetooth", "bidirectional", "wireless"), notes: "Built-in Bluetooth." },
      { ...port("AC Power In", "power", "input", "iec"), notes: "AC 100-240 V 50/60 Hz, detachable IEC cord included. 29 W typical (max not published)." },
    ],
  },
  {
    id: "2a5d0b3f-7c4e-4f68-9b21-3d0f8e6c5b02",
    deviceType: "display",
    label: "Samsung QM43C",
    shortName: "QM43C",
    manufacturer: "Samsung",
    modelNumber: "QM43C",
    referenceUrl: "https://image-us.samsung.com/SamsungUS/samsung/us/tvs/decrypted/QMC-Crystal-UHD-Series-Leaflet.pdf",
    searchTerms: ["qm43c", "qmc", "samsung signage", "43 inch", "commercial display", "tizen", "dwav"],
    widthMm: 969.5,
    heightMm: 557.8,
    depthMm: 28.5,
    weightKg: 8.8,
    powerDrawW: 121,
    voltage: "100-240V",
    unitCost: 1090,
    dwavVerified: true,
    // 43" 4K UHD QMC-series commercial display, VESA 200x200 M8. Verified 2026-09-11 against Samsung's own
    // spec sheets (see referenceUrl); CRM Products record carries the same ports + ES_Template_ID.
    ports: [
      { ...port("DP In", "displayport", "input", "displayport"), notes: "DisplayPort 1.2 (also the daisy-chain input for DP video-wall mode)." },
      { ...port("HDMI In 1", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 2", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 3", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("USB 1", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port: media playback, firmware, peripherals." },
      { ...port("USB 2", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port." },
      { ...port("Audio Out", "analog-audio", "output", "trs-eighth"), notes: "Stereo mini-jack line out. No analog audio input on this series." },
      { ...port("RS232C In", "serial", "input", "trs-eighth"), notes: "RS-232C on a 3.5 mm stereo jack; Samsung ships an RS232C (IN) gender adapter to DB9 in the box." },
      { ...port("RS232C Out", "serial", "output", "trs-eighth"), notes: "RS-232C loop-through to the next display (3.5 mm stereo jack)." },
      { ...port("LAN", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "RJ45 for MagicINFO/SSSP, MDC control and firmware." },
      { ...port("Wi-Fi", "ethernet", "bidirectional", "wireless"), addressable: true, notes: "Built-in Wi-Fi 2.4/5 GHz dual band." },
      { ...port("Bluetooth", "bluetooth", "bidirectional", "wireless"), notes: "Built-in Bluetooth." },
      { ...port("AC Power In", "power", "input", "iec"), notes: "AC 100-240 V 50/60 Hz, detachable IEC cord included. 121 W max." },
    ],
  },
  {
    id: "3b6e1c40-8d5f-4079-ac32-4e1a9f7d6c03",
    deviceType: "display",
    label: "Samsung QM55C",
    shortName: "QM55C",
    manufacturer: "Samsung",
    modelNumber: "QM55C",
    referenceUrl: "https://image-us.samsung.com/SamsungUS/samsung/us/tvs/decrypted/QMC-Crystal-UHD-Series-Leaflet.pdf",
    searchTerms: ["qm55c", "qmc", "samsung signage", "55 inch", "commercial display", "tizen", "dwav"],
    widthMm: 1237.9,
    heightMm: 708.8,
    depthMm: 28.5,
    weightKg: 15.7,
    powerDrawW: 154,
    voltage: "100-240V",
    unitCost: 1660,
    dwavVerified: true,
    // 55" 4K UHD QMC-series commercial display, VESA 200x200 M8. Verified 2026-09-11 against Samsung's own
    // spec sheets (see referenceUrl); CRM Products record carries the same ports + ES_Template_ID.
    ports: [
      { ...port("DP In", "displayport", "input", "displayport"), notes: "DisplayPort 1.2 (also the daisy-chain input for DP video-wall mode)." },
      { ...port("HDMI In 1", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 2", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 3", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("USB 1", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port: media playback, firmware, peripherals." },
      { ...port("USB 2", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port." },
      { ...port("Audio Out", "analog-audio", "output", "trs-eighth"), notes: "Stereo mini-jack line out. No analog audio input on this series." },
      { ...port("RS232C In", "serial", "input", "trs-eighth"), notes: "RS-232C on a 3.5 mm stereo jack; Samsung ships an RS232C (IN) gender adapter to DB9 in the box." },
      { ...port("RS232C Out", "serial", "output", "trs-eighth"), notes: "RS-232C loop-through to the next display (3.5 mm stereo jack)." },
      { ...port("LAN", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "RJ45 for MagicINFO/SSSP, MDC control and firmware." },
      { ...port("Wi-Fi", "ethernet", "bidirectional", "wireless"), addressable: true, notes: "Built-in Wi-Fi 2.4/5 GHz dual band." },
      { ...port("Bluetooth", "bluetooth", "bidirectional", "wireless"), notes: "Built-in Bluetooth." },
      { ...port("AC Power In", "power", "input", "iec"), notes: "AC 100-240 V 50/60 Hz, detachable IEC cord included. 154 W max." },
    ],
  },
  {
    id: "4c7f2d51-9e60-418a-bd43-5f2b0a8e7d04",
    deviceType: "display",
    label: "Samsung QM65C",
    shortName: "QM65C",
    manufacturer: "Samsung",
    modelNumber: "QM65C",
    referenceUrl: "https://image-us.samsung.com/SamsungUS/samsung/us/tvs/decrypted/QMC-Crystal-UHD-Series-Leaflet.pdf",
    searchTerms: ["qm65c", "qmc", "samsung signage", "65 inch", "commercial display", "tizen", "dwav"],
    widthMm: 1456.8,
    heightMm: 831.9,
    depthMm: 28.5,
    weightKg: 21.5,
    powerDrawW: 187,
    voltage: "100-240V",
    unitCost: 1900,
    dwavVerified: true,
    // 65" 4K UHD QMC-series commercial display, VESA 400x300 M8. Verified 2026-09-11 against Samsung's own
    // spec sheets (see referenceUrl); CRM Products record carries the same ports + ES_Template_ID.
    ports: [
      { ...port("DP In", "displayport", "input", "displayport"), notes: "DisplayPort 1.2 (also the daisy-chain input for DP video-wall mode)." },
      { ...port("HDMI In 1", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 2", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 3", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("USB 1", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port: media playback, firmware, peripherals." },
      { ...port("USB 2", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port." },
      { ...port("Audio Out", "analog-audio", "output", "trs-eighth"), notes: "Stereo mini-jack line out. No analog audio input on this series." },
      { ...port("RS232C In", "serial", "input", "trs-eighth"), notes: "RS-232C on a 3.5 mm stereo jack; Samsung ships an RS232C (IN) gender adapter to DB9 in the box." },
      { ...port("RS232C Out", "serial", "output", "trs-eighth"), notes: "RS-232C loop-through to the next display (3.5 mm stereo jack)." },
      { ...port("LAN", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "RJ45 for MagicINFO/SSSP, MDC control and firmware." },
      { ...port("Wi-Fi", "ethernet", "bidirectional", "wireless"), addressable: true, notes: "Built-in Wi-Fi 2.4/5 GHz dual band." },
      { ...port("Bluetooth", "bluetooth", "bidirectional", "wireless"), notes: "Built-in Bluetooth." },
      { ...port("AC Power In", "power", "input", "iec"), notes: "AC 100-240 V 50/60 Hz, detachable IEC cord included. 187 W max." },
    ],
  },
  {
    id: "5d803e62-af71-429b-8e54-603c1b9f8e05",
    deviceType: "display",
    label: "Samsung QM75C",
    shortName: "QM75C",
    manufacturer: "Samsung",
    modelNumber: "QM75C",
    referenceUrl: "https://image-us.samsung.com/SamsungUS/samsung/us/tvs/decrypted/QMC-Crystal-UHD-Series-Leaflet.pdf",
    searchTerms: ["qm75c", "qmc", "samsung signage", "75 inch", "commercial display", "tizen", "dwav"],
    widthMm: 1682.3,
    heightMm: 960.4,
    depthMm: 28.5,
    weightKg: 33.0,
    powerDrawW: 214.5,
    voltage: "100-240V",
    unitCost: 4300,
    dwavVerified: true,
    // 75" 4K UHD QMC-series commercial display, VESA 400x400 M8. Verified 2026-09-11 against Samsung's own
    // spec sheets (see referenceUrl); CRM Products record carries the same ports + ES_Template_ID.
    ports: [
      { ...port("DP In", "displayport", "input", "displayport"), notes: "DisplayPort 1.2 (also the daisy-chain input for DP video-wall mode)." },
      { ...port("HDMI In 1", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 2", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 3", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("USB 1", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port: media playback, firmware, peripherals." },
      { ...port("USB 2", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port." },
      { ...port("Audio Out", "analog-audio", "output", "trs-eighth"), notes: "Stereo mini-jack line out. No analog audio input on this series." },
      { ...port("RS232C In", "serial", "input", "trs-eighth"), notes: "RS-232C on a 3.5 mm stereo jack; Samsung ships an RS232C (IN) gender adapter to DB9 in the box." },
      { ...port("RS232C Out", "serial", "output", "trs-eighth"), notes: "RS-232C loop-through to the next display (3.5 mm stereo jack)." },
      { ...port("LAN", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "RJ45 for MagicINFO/SSSP, MDC control and firmware." },
      { ...port("Wi-Fi", "ethernet", "bidirectional", "wireless"), addressable: true, notes: "Built-in Wi-Fi 2.4/5 GHz dual band." },
      { ...port("Bluetooth", "bluetooth", "bidirectional", "wireless"), notes: "Built-in Bluetooth." },
      { ...port("AC Power In", "power", "input", "iec"), notes: "AC 100-240 V 50/60 Hz, detachable IEC cord included. 214.5 W max." },
    ],
  },
  {
    id: "6e914f73-b082-43ac-9f65-714d2ca09f06",
    deviceType: "display",
    label: "Samsung QM85C",
    shortName: "QM85C",
    manufacturer: "Samsung",
    modelNumber: "QM85C",
    referenceUrl: "https://image-us.samsung.com/SamsungUS/samsung/us/tvs/decrypted/QMC-Crystal-UHD-Series-Leaflet.pdf",
    searchTerms: ["qm85c", "qmc", "samsung signage", "85 inch", "commercial display", "tizen", "dwav"],
    widthMm: 1904.3,
    heightMm: 1085.3,
    depthMm: 28.5,
    weightKg: 41.4,
    powerDrawW: 330,
    voltage: "100-240V",
    unitCost: 6300,
    dwavVerified: true,
    // 85" 4K UHD QMC-series commercial display, VESA 400x400 M8. Verified 2026-09-11 against Samsung's own
    // spec sheets (see referenceUrl); CRM Products record carries the same ports + ES_Template_ID.
    ports: [
      { ...port("DP In", "displayport", "input", "displayport"), notes: "DisplayPort 1.2 (also the daisy-chain input for DP video-wall mode)." },
      { ...port("HDMI In 1", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 2", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 3", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("USB 1", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port: media playback, firmware, peripherals." },
      { ...port("USB 2", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port." },
      { ...port("Audio Out", "analog-audio", "output", "trs-eighth"), notes: "Stereo mini-jack line out. No analog audio input on this series." },
      { ...port("RS232C In", "serial", "input", "trs-eighth"), notes: "RS-232C on a 3.5 mm stereo jack; Samsung ships an RS232C (IN) gender adapter to DB9 in the box." },
      { ...port("RS232C Out", "serial", "output", "trs-eighth"), notes: "RS-232C loop-through to the next display (3.5 mm stereo jack)." },
      { ...port("LAN", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "RJ45 for MagicINFO/SSSP, MDC control and firmware." },
      { ...port("Wi-Fi", "ethernet", "bidirectional", "wireless"), addressable: true, notes: "Built-in Wi-Fi 2.4/5 GHz dual band." },
      { ...port("Bluetooth", "bluetooth", "bidirectional", "wireless"), notes: "Built-in Bluetooth." },
      { ...port("AC Power In", "power", "input", "iec"), notes: "AC 100-240 V 50/60 Hz, detachable IEC cord included. 330 W max." },
    ],
  },
  {
    id: "7fa25084-c193-44bd-a076-825e3db1a007",
    deviceType: "display",
    label: "Samsung QM98C",
    shortName: "QM98C",
    manufacturer: "Samsung",
    modelNumber: "QM98C",
    referenceUrl: "https://image-us.samsung.com/SamsungUS/samsung/us/tvs/decrypted/Samsung-QH98C_QM98C-Enterprise-Leaflet.pdf",
    searchTerms: ["qm98c", "qmc", "samsung signage", "98 inch", "commercial display", "tizen", "dwav"],
    widthMm: 2193.2,
    heightMm: 1248.8,
    depthMm: 48.1,
    weightKg: 56.3,
    powerDrawW: 363,
    voltage: "100-240V",
    unitCost: 8999,
    dwavVerified: true,
    // 98" 4K UHD QMC-series commercial display, VESA 600x400 M8. Verified 2026-09-11 against Samsung's own
    // spec sheets (see referenceUrl); CRM Products record carries the same ports + ES_Template_ID.
    ports: [
      { ...port("DP In", "displayport", "input", "displayport"), notes: "DisplayPort 1.2 (also the daisy-chain input for DP video-wall mode)." },
      { ...port("HDMI In 1", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 2", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 3", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("USB 1", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port: media playback, firmware, peripherals." },
      { ...port("USB 2", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port." },
      { ...port("Audio Out", "analog-audio", "output", "trs-eighth"), notes: "Stereo mini-jack line out. No analog audio input on this series." },
      { ...port("RS232C In", "serial", "input", "trs-eighth"), notes: "RS-232C on a 3.5 mm stereo jack; Samsung ships an RS232C (IN) gender adapter to DB9 in the box." },
      { ...port("RS232C Out", "serial", "output", "trs-eighth"), notes: "RS-232C loop-through to the next display (3.5 mm stereo jack)." },
      { ...port("LAN", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "RJ45 for MagicINFO/SSSP, MDC control and firmware." },
      { ...port("Wi-Fi", "ethernet", "bidirectional", "wireless"), addressable: true, notes: "Built-in Wi-Fi 2.4/5 GHz dual band." },
      { ...port("Bluetooth", "bluetooth", "bidirectional", "wireless"), notes: "Built-in Bluetooth." },
      { ...port("AC Power In", "power", "input", "iec"), notes: "AC 100-240 V 50/60 Hz, detachable IEC cord included. 363 W max." },
    ],
  },
];
