import { port } from "./_helpers";
import type { DeviceTemplate } from "../types";

/**
 * DWAV-verified device templates, compiled from the CRM Device Ports subform.
 * Ship this file via a normal push+deploy so every DWAV EasySchematic user gets
 * these automatically -- no manual "Import from JSON" step, no localStorage
 * dependency. Each device's `id` should be treated as stable: it round-trips
 * back to the CRM product's compiled template.
 *
 * Do not edit by hand for anything CRM-managed -- regenerate from CRM via the
 * Design Studio compiler once it exists. See dwav-design-studio/docs/CREATED.md.
 */
export const templates: DeviceTemplate[] = [
  {
    id: "37e3b485-ed14-4d44-83d7-703cc6b6df3f",
    dwavVerified: true,
    deviceType: "wired-mic",
    label: "Audio-Technica BP3600",
    manufacturer: "Audio-Technica",
    modelNumber: "BP3600",
    referenceUrl: "https://www.audio-technica.com/en-us/bp3600",
    searchTerms: ["bp3600", "immersive audio", "microphone array", "8-channel", "atmos mic", "dwav"],
    unitCost: 8472,   // MSRP — DWAV rule: never dealer cost in this public file
    ports: [
      {
        ...port("Audio Out (8-ch)", "analog-audio", "output", "multipin"),
        channelCount: 8,
        notes:
          "LEMO 2B 10-pin multi-out on mic body. Ships with LEMO-to-XLRM (x8) breakout cable for 8 discrete channels; each channel requires 48V phantom from the downstream device.",
      },
    ],
  },
  {
    id: "7af08446-b1a9-49ef-a0b7-88b6d789be31",
    dwavVerified: true,
    deviceType: "wired-mic",
    label: "Audio-Technica ATND1061DAN",
    manufacturer: "Audio-Technica",
    modelNumber: "ATND1061DAN",
    referenceUrl: "https://www.audio-technica.com/en-us/atnd1061",
    searchTerms: ["atnd1061", "beamforming", "ceiling array", "dante", "poe", "dwav"],
    widthMm: 227.5,
    depthMm: 227.5,
    heightMm: 30,
    weightKg: 1.25,
    unitCost: 4844,
    ports: [
      {
        ...port("Dante Primary", "dante", "bidirectional", "rj45"),
        addressable: true,
        poeDrawW: 7,
        notes:
          "Carries Dante audio + mic control data (100 Mbps control over 1 Gbps link). PoE input, IEEE 802.3af Class 0, 7W max.",
      },
      {
        ...port("Dante Secondary", "dante", "bidirectional", "rj45"),
        addressable: true,
        notes: "Redundant Dante network port (Single Cable or Split mode).",
      },
      {
        ...port("Analog Input", "analog-audio", "input", "phoenix"),
        notes: "Euroblock 3-pin. External analog mic/source input.",
      },
      {
        ...port("Analog Output", "analog-audio", "output", "phoenix"),
        notes: "Euroblock 3-pin. Local analog output for non-Dante integration.",
      },
      {
        ...port("GPI", "contact-closure", "input", "phoenix"),
        notes: "Euroblock 3-pin general-purpose trigger input.",
      },
    ],
  },
  {
    id: "46f26a4d-ce40-4f16-b042-a4e34c1c4d36",
    dwavVerified: true,
    deviceType: "speaker",
    label: "Martin Audio ACS-40TS-W",
    manufacturer: "Martin Audio",
    modelNumber: "ACS-40TS-W",
    referenceUrl: "https://martin-audio.com/products/loudspeakers/acs-40ts",
    searchTerms: ["acs-40ts", "adorn", "ceiling speaker", "70v", "100v", "dwav"],
    widthMm: 221,
    depthMm: 115,
    heightMm: 30,
    weightKg: 2.2,
    unitCost: 135,
    ports: [
      {
        ...port("Audio In", "speaker-level", "input", "terminal-block"),
        notes:
          "Ceramic terminal block, positions 1&2 (+/-). 70V taps: 20/10/5/2.5W; 100V taps: 20/10/5W; 16-ohm direct also selectable.",
      },
      {
        ...port("Link Out", "speaker-level", "output", "terminal-block"),
        notes: "Ceramic terminal block, positions 3&4 (+/-). Loop-through to next speaker in a daisy chain.",
      },
    ],
  },
  {
    id: "1f4c9a2e-6b3d-4e57-8a10-2c9e7d5b4a01",
    deviceType: "display",
    label: "Samsung QM32C",
    shortName: "QM32C",
    manufacturer: "Samsung",
    modelNumber: "QM32C",
    referenceUrl: "https://images.samsung.com/is/content/samsung/assets/de/business/displays/pdf/Datenblatt_Smart-Signage_LH32QMCEBGCXEN.pdf",
    searchTerms: ["qm32c", "qmc", "samsung signage", "32 inch", "commercial display", "tizen", "dwav"],
    widthMm: 727.3,
    heightMm: 421.9,
    depthMm: 28.5,
    weightKg: 5.2,
    powerDrawW: 29,
    voltage: "100-240V",
    unitCost: 840,
    dwavVerified: true,
    // 32" Full HD QMC-series commercial display, VESA 100x100 M4. Verified 2026-09-11 against Samsung's own
    // spec sheets (see referenceUrl); CRM Products record carries the same ports + ES_Template_ID.
    ports: [
      { ...port("HDMI In 1", "hdmi", "input", "hdmi"), notes: "HDMI (HDCP 2.2)" },
      { ...port("HDMI In 2", "hdmi", "input", "hdmi"), notes: "HDMI (HDCP 2.2)" },
      { ...port("HDMI In 3", "hdmi", "input", "hdmi"), notes: "HDMI (HDCP 2.2)" },
      { ...port("USB 1", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port: media playback, firmware, peripherals." },
      { ...port("USB 2", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port." },
      { ...port("Audio Out", "analog-audio", "output", "trs-eighth"), notes: "Stereo mini-jack line out. No analog audio input on this series." },
      { ...port("RS232C In", "serial", "input", "trs-eighth"), notes: "RS-232C on a 3.5 mm stereo jack; Samsung ships an RS232C (IN) gender adapter to DB9 in the box." },
      { ...port("RS232C Out", "serial", "output", "trs-eighth"), notes: "RS-232C loop-through to the next display (3.5 mm stereo jack)." },
      { ...port("LAN", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "RJ45 for MagicINFO/SSSP, MDC control and firmware." },
      { ...port("Wi-Fi", "ethernet", "bidirectional", "wireless"), addressable: true, notes: "Built-in Wi-Fi 2.4/5 GHz dual band." },
      { ...port("Bluetooth", "bluetooth", "bidirectional", "wireless"), notes: "Built-in Bluetooth." },
      { ...port("AC Power In", "power", "input", "iec"), notes: "AC 100-240 V 50/60 Hz, detachable IEC cord included. 29 W typical (max not published)." },
    ],
  },
  {
    id: "2a5d0b3f-7c4e-4f68-9b21-3d0f8e6c5b02",
    deviceType: "display",
    label: "Samsung QM43C",
    shortName: "QM43C",
    manufacturer: "Samsung",
    modelNumber: "QM43C",
    referenceUrl: "https://image-us.samsung.com/SamsungUS/samsung/us/tvs/decrypted/QMC-Crystal-UHD-Series-Leaflet.pdf",
    searchTerms: ["qm43c", "qmc", "samsung signage", "43 inch", "commercial display", "tizen", "dwav"],
    widthMm: 969.5,
    heightMm: 557.8,
    depthMm: 28.5,
    weightKg: 8.8,
    powerDrawW: 121,
    voltage: "100-240V",
    unitCost: 1090,
    dwavVerified: true,
    // 43" 4K UHD QMC-series commercial display, VESA 200x200 M8. Verified 2026-09-11 against Samsung's own
    // spec sheets (see referenceUrl); CRM Products record carries the same ports + ES_Template_ID.
    ports: [
      { ...port("DP In", "displayport", "input", "displayport"), notes: "DisplayPort 1.2 (also the daisy-chain input for DP video-wall mode)." },
      { ...port("HDMI In 1", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 2", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 3", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("USB 1", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port: media playback, firmware, peripherals." },
      { ...port("USB 2", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port." },
      { ...port("Audio Out", "analog-audio", "output", "trs-eighth"), notes: "Stereo mini-jack line out. No analog audio input on this series." },
      { ...port("RS232C In", "serial", "input", "trs-eighth"), notes: "RS-232C on a 3.5 mm stereo jack; Samsung ships an RS232C (IN) gender adapter to DB9 in the box." },
      { ...port("RS232C Out", "serial", "output", "trs-eighth"), notes: "RS-232C loop-through to the next display (3.5 mm stereo jack)." },
      { ...port("LAN", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "RJ45 for MagicINFO/SSSP, MDC control and firmware." },
      { ...port("Wi-Fi", "ethernet", "bidirectional", "wireless"), addressable: true, notes: "Built-in Wi-Fi 2.4/5 GHz dual band." },
      { ...port("Bluetooth", "bluetooth", "bidirectional", "wireless"), notes: "Built-in Bluetooth." },
      { ...port("AC Power In", "power", "input", "iec"), notes: "AC 100-240 V 50/60 Hz, detachable IEC cord included. 121 W max." },
    ],
  },
  {
    id: "3b6e1c40-8d5f-4079-ac32-4e1a9f7d6c03",
    deviceType: "display",
    label: "Samsung QM55C",
    shortName: "QM55C",
    manufacturer: "Samsung",
    modelNumber: "QM55C",
    referenceUrl: "https://image-us.samsung.com/SamsungUS/samsung/us/tvs/decrypted/QMC-Crystal-UHD-Series-Leaflet.pdf",
    searchTerms: ["qm55c", "qmc", "samsung signage", "55 inch", "commercial display", "tizen", "dwav"],
    widthMm: 1237.9,
    heightMm: 708.8,
    depthMm: 28.5,
    weightKg: 15.7,
    powerDrawW: 154,
    voltage: "100-240V",
    unitCost: 1660,
    dwavVerified: true,
    // 55" 4K UHD QMC-series commercial display, VESA 200x200 M8. Verified 2026-09-11 against Samsung's own
    // spec sheets (see referenceUrl); CRM Products record carries the same ports + ES_Template_ID.
    ports: [
      { ...port("DP In", "displayport", "input", "displayport"), notes: "DisplayPort 1.2 (also the daisy-chain input for DP video-wall mode)." },
      { ...port("HDMI In 1", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 2", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 3", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("USB 1", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port: media playback, firmware, peripherals." },
      { ...port("USB 2", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port." },
      { ...port("Audio Out", "analog-audio", "output", "trs-eighth"), notes: "Stereo mini-jack line out. No analog audio input on this series." },
      { ...port("RS232C In", "serial", "input", "trs-eighth"), notes: "RS-232C on a 3.5 mm stereo jack; Samsung ships an RS232C (IN) gender adapter to DB9 in the box." },
      { ...port("RS232C Out", "serial", "output", "trs-eighth"), notes: "RS-232C loop-through to the next display (3.5 mm stereo jack)." },
      { ...port("LAN", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "RJ45 for MagicINFO/SSSP, MDC control and firmware." },
      { ...port("Wi-Fi", "ethernet", "bidirectional", "wireless"), addressable: true, notes: "Built-in Wi-Fi 2.4/5 GHz dual band." },
      { ...port("Bluetooth", "bluetooth", "bidirectional", "wireless"), notes: "Built-in Bluetooth." },
      { ...port("AC Power In", "power", "input", "iec"), notes: "AC 100-240 V 50/60 Hz, detachable IEC cord included. 154 W max." },
    ],
  },
  {
    id: "4c7f2d51-9e60-418a-bd43-5f2b0a8e7d04",
    deviceType: "display",
    label: "Samsung QM65C",
    shortName: "QM65C",
    manufacturer: "Samsung",
    modelNumber: "QM65C",
    referenceUrl: "https://image-us.samsung.com/SamsungUS/samsung/us/tvs/decrypted/QMC-Crystal-UHD-Series-Leaflet.pdf",
    searchTerms: ["qm65c", "qmc", "samsung signage", "65 inch", "commercial display", "tizen", "dwav"],
    widthMm: 1456.8,
    heightMm: 831.9,
    depthMm: 28.5,
    weightKg: 21.5,
    powerDrawW: 187,
    voltage: "100-240V",
    unitCost: 1900,
    dwavVerified: true,
    // 65" 4K UHD QMC-series commercial display, VESA 400x300 M8. Verified 2026-09-11 against Samsung's own
    // spec sheets (see referenceUrl); CRM Products record carries the same ports + ES_Template_ID.
    ports: [
      { ...port("DP In", "displayport", "input", "displayport"), notes: "DisplayPort 1.2 (also the daisy-chain input for DP video-wall mode)." },
      { ...port("HDMI In 1", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 2", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 3", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("USB 1", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port: media playback, firmware, peripherals." },
      { ...port("USB 2", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port." },
      { ...port("Audio Out", "analog-audio", "output", "trs-eighth"), notes: "Stereo mini-jack line out. No analog audio input on this series." },
      { ...port("RS232C In", "serial", "input", "trs-eighth"), notes: "RS-232C on a 3.5 mm stereo jack; Samsung ships an RS232C (IN) gender adapter to DB9 in the box." },
      { ...port("RS232C Out", "serial", "output", "trs-eighth"), notes: "RS-232C loop-through to the next display (3.5 mm stereo jack)." },
      { ...port("LAN", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "RJ45 for MagicINFO/SSSP, MDC control and firmware." },
      { ...port("Wi-Fi", "ethernet", "bidirectional", "wireless"), addressable: true, notes: "Built-in Wi-Fi 2.4/5 GHz dual band." },
      { ...port("Bluetooth", "bluetooth", "bidirectional", "wireless"), notes: "Built-in Bluetooth." },
      { ...port("AC Power In", "power", "input", "iec"), notes: "AC 100-240 V 50/60 Hz, detachable IEC cord included. 187 W max." },
    ],
  },
  {
    id: "5d803e62-af71-429b-8e54-603c1b9f8e05",
    deviceType: "display",
    label: "Samsung QM75C",
    shortName: "QM75C",
    manufacturer: "Samsung",
    modelNumber: "QM75C",
    referenceUrl: "https://image-us.samsung.com/SamsungUS/samsung/us/tvs/decrypted/QMC-Crystal-UHD-Series-Leaflet.pdf",
    searchTerms: ["qm75c", "qmc", "samsung signage", "75 inch", "commercial display", "tizen", "dwav"],
    widthMm: 1682.3,
    heightMm: 960.4,
    depthMm: 28.5,
    weightKg: 33.0,
    powerDrawW: 214.5,
    voltage: "100-240V",
    unitCost: 4300,
    dwavVerified: true,
    // 75" 4K UHD QMC-series commercial display, VESA 400x400 M8. Verified 2026-09-11 against Samsung's own
    // spec sheets (see referenceUrl); CRM Products record carries the same ports + ES_Template_ID.
    ports: [
      { ...port("DP In", "displayport", "input", "displayport"), notes: "DisplayPort 1.2 (also the daisy-chain input for DP video-wall mode)." },
      { ...port("HDMI In 1", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 2", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 3", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("USB 1", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port: media playback, firmware, peripherals." },
      { ...port("USB 2", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port." },
      { ...port("Audio Out", "analog-audio", "output", "trs-eighth"), notes: "Stereo mini-jack line out. No analog audio input on this series." },
      { ...port("RS232C In", "serial", "input", "trs-eighth"), notes: "RS-232C on a 3.5 mm stereo jack; Samsung ships an RS232C (IN) gender adapter to DB9 in the box." },
      { ...port("RS232C Out", "serial", "output", "trs-eighth"), notes: "RS-232C loop-through to the next display (3.5 mm stereo jack)." },
      { ...port("LAN", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "RJ45 for MagicINFO/SSSP, MDC control and firmware." },
      { ...port("Wi-Fi", "ethernet", "bidirectional", "wireless"), addressable: true, notes: "Built-in Wi-Fi 2.4/5 GHz dual band." },
      { ...port("Bluetooth", "bluetooth", "bidirectional", "wireless"), notes: "Built-in Bluetooth." },
      { ...port("AC Power In", "power", "input", "iec"), notes: "AC 100-240 V 50/60 Hz, detachable IEC cord included. 214.5 W max." },
    ],
  },
  {
    id: "6e914f73-b082-43ac-9f65-714d2ca09f06",
    deviceType: "display",
    label: "Samsung QM85C",
    shortName: "QM85C",
    manufacturer: "Samsung",
    modelNumber: "QM85C",
    referenceUrl: "https://image-us.samsung.com/SamsungUS/samsung/us/tvs/decrypted/QMC-Crystal-UHD-Series-Leaflet.pdf",
    searchTerms: ["qm85c", "qmc", "samsung signage", "85 inch", "commercial display", "tizen", "dwav"],
    widthMm: 1904.3,
    heightMm: 1085.3,
    depthMm: 28.5,
    weightKg: 41.4,
    powerDrawW: 330,
    voltage: "100-240V",
    unitCost: 6300,
    dwavVerified: true,
    // 85" 4K UHD QMC-series commercial display, VESA 400x400 M8. Verified 2026-09-11 against Samsung's own
    // spec sheets (see referenceUrl); CRM Products record carries the same ports + ES_Template_ID.
    ports: [
      { ...port("DP In", "displayport", "input", "displayport"), notes: "DisplayPort 1.2 (also the daisy-chain input for DP video-wall mode)." },
      { ...port("HDMI In 1", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 2", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 3", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("USB 1", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port: media playback, firmware, peripherals." },
      { ...port("USB 2", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port." },
      { ...port("Audio Out", "analog-audio", "output", "trs-eighth"), notes: "Stereo mini-jack line out. No analog audio input on this series." },
      { ...port("RS232C In", "serial", "input", "trs-eighth"), notes: "RS-232C on a 3.5 mm stereo jack; Samsung ships an RS232C (IN) gender adapter to DB9 in the box." },
      { ...port("RS232C Out", "serial", "output", "trs-eighth"), notes: "RS-232C loop-through to the next display (3.5 mm stereo jack)." },
      { ...port("LAN", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "RJ45 for MagicINFO/SSSP, MDC control and firmware." },
      { ...port("Wi-Fi", "ethernet", "bidirectional", "wireless"), addressable: true, notes: "Built-in Wi-Fi 2.4/5 GHz dual band." },
      { ...port("Bluetooth", "bluetooth", "bidirectional", "wireless"), notes: "Built-in Bluetooth." },
      { ...port("AC Power In", "power", "input", "iec"), notes: "AC 100-240 V 50/60 Hz, detachable IEC cord included. 330 W max." },
    ],
  },
  {
    id: "7fa25084-c193-44bd-a076-825e3db1a007",
    deviceType: "display",
    label: "Samsung QM98C",
    shortName: "QM98C",
    manufacturer: "Samsung",
    modelNumber: "QM98C",
    referenceUrl: "https://image-us.samsung.com/SamsungUS/samsung/us/tvs/decrypted/Samsung-QH98C_QM98C-Enterprise-Leaflet.pdf",
    searchTerms: ["qm98c", "qmc", "samsung signage", "98 inch", "commercial display", "tizen", "dwav"],
    widthMm: 2193.2,
    heightMm: 1248.8,
    depthMm: 48.1,
    weightKg: 56.3,
    powerDrawW: 363,
    voltage: "100-240V",
    unitCost: 8999,
    dwavVerified: true,
    // 98" 4K UHD QMC-series commercial display, VESA 600x400 M8. Verified 2026-09-11 against Samsung's own
    // spec sheets (see referenceUrl); CRM Products record carries the same ports + ES_Template_ID.
    ports: [
      { ...port("DP In", "displayport", "input", "displayport"), notes: "DisplayPort 1.2 (also the daisy-chain input for DP video-wall mode)." },
      { ...port("HDMI In 1", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 2", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("HDMI In 3", "hdmi", "input", "hdmi"), notes: "HDMI 2.0" },
      { ...port("USB 1", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port: media playback, firmware, peripherals." },
      { ...port("USB 2", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 host port." },
      { ...port("Audio Out", "analog-audio", "output", "trs-eighth"), notes: "Stereo mini-jack line out. No analog audio input on this series." },
      { ...port("RS232C In", "serial", "input", "trs-eighth"), notes: "RS-232C on a 3.5 mm stereo jack; Samsung ships an RS232C (IN) gender adapter to DB9 in the box." },
      { ...port("RS232C Out", "serial", "output", "trs-eighth"), notes: "RS-232C loop-through to the next display (3.5 mm stereo jack)." },
      { ...port("LAN", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "RJ45 for MagicINFO/SSSP, MDC control and firmware." },
      { ...port("Wi-Fi", "ethernet", "bidirectional", "wireless"), addressable: true, notes: "Built-in Wi-Fi 2.4/5 GHz dual band." },
      { ...port("Bluetooth", "bluetooth", "bidirectional", "wireless"), notes: "Built-in Bluetooth." },
      { ...port("AC Power In", "power", "input", "iec"), notes: "AC 100-240 V 50/60 Hz, detachable IEC cord included. 363 W max." },
    ],
  },
  {
    id: "0b0ca970-834f-47a8-9e1c-84fd9d6ff3e8",
    deviceType: "video-bar",
    label: "Logitech Rally Bar",
    shortName: "Rally Bar",
    manufacturer: "Logitech",
    modelNumber: "960-001312",
    referenceUrl: "https://hub.sync.logitech.com/Rally-Bar/post/rally-bar---specifications-y6v2UoNh2YbpNKh",
    searchTerms: ["rally bar", "960-001312", "960-001308", "video bar", "logitech", "collabos", "ptz", "conference camera", "dwav"],
    widthMm: 910,
    heightMm: 164,
    depthMm: 130.5,
    weightKg: 7.08,
    powerDrawW: 90,
    voltage: "100-240V",
    unitCost: 5611.11,
    dwavVerified: true,
    // All-in-one video bar for medium/large rooms: 4K PTZ camera (motorized pan +/-25, tilt +/-15, 15x HD zoom = 5x optical x 3x digital; FOV 90 D / 82.1 H / 52.2 V), AI Viewfinder (174 D), 6-mic beamforming array (23 ft pickup), 2 x 70 mm speakers (99 dB SPL @ 8 W, 1/2 m). 910 x 164 (with table stand) x 130.5 mm, lens depth 28.8 mm, 7.08 kg. Mounts: TV Mount for Video Bars 952-000041, Wall Mount for Video Bars 952-000044.
    // Verified 2026-09-12 against Logitech's own spec page (referenceUrl); the CRM Products record
    // carries the same ports plus the camera facts (Cam_* fields) and this id as ES_Template_ID.
    ports: [
      { ...port("HDMI Out 1", "hdmi", "output", "hdmi"), notes: "HDMI 1.4 to the room display; 1080p60 max output (no 4K out)." },
      { ...port("HDMI Out 2", "hdmi", "output", "hdmi"), notes: "HDMI 1.4, second display; 1080p60 max." },
      { ...port("HDMI In", "hdmi", "input", "hdmi"), notes: "HDMI 1.4 content / BYOD input; 1080p60 passthrough (no 4K passthrough)." },
      { ...port("USB-C (PC)", "usb", "bidirectional", "usb-c"), notes: "USB 3.0 Type-C: the meeting-room PC / laptop connection in USB (PC) and BYOD modes. 2.2 m USB-A to USB-C cable included." },
      { ...port("USB-A 1", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 Type-A host port: Logitech Tap (USB), Swytch, DisplayLink adapter for a third display." },
      { ...port("USB-A 2", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 Type-A host port." },
      { ...port("USB-A 3", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 Type-A host port." },
      { ...port("LAN", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "10/100/1G Ethernet: appliance-mode meetings, Tap IP, Logitech Sync management." },
      { ...port("Wi-Fi", "ethernet", "bidirectional", "wireless"), addressable: true, notes: "802.11a/b/g/n/ac MIMO." },
      { ...port("Bluetooth", "bluetooth", "bidirectional", "wireless"), notes: "Bluetooth Low Energy for the included remote control." },
      { ...port("Mic Pod In", "analog-audio", "input", "multipin"), notes: "Proprietary Logitech 12-pin Rally Mic Pod input: up to 4 Rally Mic Pods, 2 Mic Pod Hubs, 2 x 10 m extension cables." },
      { ...port("DC Power In", "power", "input", "barrel"), notes: "19 V DC from the included 90 W auto-sensing supply (PN 993-001943, 100-240 V, 4.74 A); 1.5 m DC lead. Thermal 57 BTU/hr idle, 64 in meeting." },
    ],
  },
  {
    id: "742dbf25-0edb-446e-93ff-a8977ac08e07",
    deviceType: "video-bar",
    label: "Logitech Rally Bar Mini",
    shortName: "Rally Bar Mini",
    manufacturer: "Logitech",
    modelNumber: "960-001336",
    referenceUrl: "https://hub.sync.logitech.com/rallybarmini/post/specifications---rally-bar-mini-K3ptSACa3kgpz8h",
    searchTerms: ["rally bar mini", "960-001336", "video bar", "logitech", "collabos", "ptz", "conference camera", "dwav"],
    widthMm: 719,
    heightMm: 91.4,
    depthMm: 101,
    weightKg: 4.03,
    powerDrawW: 90,
    voltage: "100-240V",
    unitCost: 3499,
    dwavVerified: true,
    // All-in-one video bar for small/medium rooms: 4K camera, motorized pan +/-25 / tilt +/-15, 4x HD digital zoom, FOV 120 D / 113 H / 80.7 V (163 x 110 total room coverage), AI Viewfinder, 6-mic beamforming array (23 ft), 70 mm woofer + 2 x 1.5 in mid-range (99 dB SPL @ 8 W, 1/2 m). 719 x 91.4 x 101 mm, 4.03 kg. Mounts: TV Mount for Video Bars 952-000041, Wall Mount for Video Bars 952-000044.
    // Verified 2026-09-12 against Logitech's own spec page (referenceUrl); the CRM Products record
    // carries the same ports plus the camera facts (Cam_* fields) and this id as ES_Template_ID.
    ports: [
      { ...port("HDMI Out 1", "hdmi", "output", "hdmi"), notes: "HDMI 1.4 to the room display; 1080p60 max output (no 4K out)." },
      { ...port("HDMI Out 2", "hdmi", "output", "hdmi"), notes: "HDMI 1.4, second display; 1080p60 max." },
      { ...port("HDMI In", "hdmi", "input", "hdmi"), notes: "HDMI 1.4 content / BYOD input; 1080p60 passthrough (no 4K passthrough)." },
      { ...port("USB-C (PC)", "usb", "bidirectional", "usb-c"), notes: "USB 3.0 Type-C: the meeting-room PC / laptop connection in USB (PC) and BYOD modes. 2.2 m USB-A to USB-C cable included." },
      { ...port("USB-A 1", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 Type-A host port: Logitech Tap (USB), Swytch, DisplayLink adapter for a third display." },
      { ...port("USB-A 2", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 Type-A host port." },
      { ...port("USB-A 3", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 Type-A host port." },
      { ...port("LAN", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "10/100/1G Ethernet: appliance-mode meetings, Tap IP, Logitech Sync management." },
      { ...port("Wi-Fi", "ethernet", "bidirectional", "wireless"), addressable: true, notes: "802.11a/b/g/n/ac MIMO." },
      { ...port("Bluetooth", "bluetooth", "bidirectional", "wireless"), notes: "Bluetooth Low Energy for the included remote control." },
      { ...port("Mic Pod In", "analog-audio", "input", "multipin"), notes: "Proprietary Logitech 12-pin Rally Mic Pod input: up to 3 Rally Mic Pods, 2 Mic Pod Hubs, 2 x 10 m extension cables." },
      { ...port("DC Power In", "power", "input", "barrel"), notes: "19 V DC from the included 90 W auto-sensing supply (PN 993-001943, 100-240 V, 4.74 A); 1.5 m DC lead. Thermal 57 BTU/hr idle, 64 in meeting." },
    ],
  },
  {
    id: "cf1ac7fd-28c6-406c-b171-4f70571879c8",
    deviceType: "video-bar",
    label: "Logitech Rally Bar Huddle",
    shortName: "Rally Bar Huddle",
    manufacturer: "Logitech",
    modelNumber: "960-001577",
    referenceUrl: "https://hub.sync.logitech.com/rallybarhuddle/post/rally-bar-huddle-technical-specifications-tswoyEOkgn1Aja7",
    searchTerms: ["rally bar huddle", "960-001577", "960-001485", "video bar", "logitech", "collabos", "huddle room", "conference camera", "dwav"],
    widthMm: 549.6,
    heightMm: 78.9,
    depthMm: 76,
    weightKg: 1.8,
    powerDrawW: 40,
    voltage: "100-240V",
    unitCost: 2480.56,
    dwavVerified: true,
    // All-in-one video bar for huddle/small rooms: 4K digital-PTZ camera (digital pan +/-48 / tilt +/-32 at 4x, 4x digital zoom; FOV 120 D / 113 H / 80 V), motorized privacy shutter, 6-mic array (23 ft), 55 mm ported speaker (8 W). 549.6 x 78.9 x 76 mm, 1.8 kg. Multi Mount in the box (wall / table / display); TV Mount Adapter Kit 952-000248 for above/below a display. No Rally Mic Pod input.
    // Verified 2026-09-12 against Logitech's own spec page (referenceUrl); the CRM Products record
    // carries the same ports plus the camera facts (Cam_* fields) and this id as ES_Template_ID.
    ports: [
      { ...port("HDMI Out", "hdmi", "output", "hdmi"), notes: "HDMI 1.4 to the room display; 1080p max output. One display natively (second via a USB-to-Display adapter)." },
      { ...port("HDMI In", "hdmi", "input", "hdmi"), notes: "HDMI 1.4 content / BYOD input; 1080p60 passthrough (no 4K passthrough)." },
      { ...port("USB-C (PC)", "usb", "bidirectional", "usb-c"), notes: "USB 3.1 Type-C: the meeting-room PC / laptop connection in USB (PC) and BYOD modes. 2.2 m USB-A to USB-C cable included." },
      { ...port("USB-A", "usb", "bidirectional", "usb-a"), notes: "USB 3.1 Type-A host port: Logitech Tap (USB), USB-to-Display adapter for a second display." },
      { ...port("LAN", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "10/100/1G Ethernet: appliance-mode meetings, Tap IP, Logitech Sync management. IPv4/IPv6." },
      { ...port("Wi-Fi", "ethernet", "bidirectional", "wireless"), addressable: true, notes: "802.11a/b/g/n/ac." },
      { ...port("Bluetooth", "bluetooth", "bidirectional", "wireless"), notes: "Bluetooth Low Energy." },
      { ...port("DC Power In", "power", "input", "barrel"), notes: "19 V DC from the included auto-sensing supply (100-240 V, 2.1 A = 40 W rating); 1.5 m DC lead. No external Rally Mic Pod input on this model." },
    ],
  },
  {
    id: "5f872f2b-146e-4369-a202-ba66250f5e9f",
    deviceType: "camera",
    label: "Cisco Quad Camera",
    shortName: "Quad Camera",
    manufacturer: "Cisco",
    modelNumber: "CS-QUADCAM=",
    referenceUrl: "https://www.cisco.com/c/en/us/products/collateral/collaboration-endpoints/spark-room-kit-series/datasheet-c78-738752.html",
    searchTerms: ["quad camera", "cs-quadcam", "cs-quadcam2", "room kit plus", "room kit pro", "webex", "speaker track", "cisco camera", "dwav"],
    widthMm: 950,
    heightMm: 120,
    depthMm: 102.5,
    weightKg: 4.8,
    powerDrawW: 70,
    voltage: "12V DC (100-240V adapter)",
    unitCost: 16238.48,
    dwavVerified: true,
    // Camera + speaker bar for the Room Kit Plus / Pro and SX80 integrator package: four 5K sensors (one 83 deg
    // wide lens + three 50 deg tele lenses, 5x digital zoom, 51.5 deg vertical), 6-element mic array for speaker
    // tracking ONLY (no far-end audio pickup), internal speakers 70 Hz-20 kHz / 90 dB SPL. 950 x 120 x 102.5 mm,
    // 4.8 kg. Needs a Cisco codec - it is not an all-in-one. Also sold as CS-QUADCAM+ / CS-QUADCAM2 (First
    // Light) / CS-QUADCAM2-C+ (Carbon Black): same device. Verified 2026-09-14 against Cisco's Room Kit Plus data
    // sheet, installation guide connector legend and CAD drawing D15386.01; CRM Products carries the same ports.
    ports: [
      { ...port("HDMI Out 1", "hdmi", "output", "hdmi"), notes: "Camera video to the codec camera input (Codec Plus / SX80), 1080p60. High Speed HDMI 1.4b cable." },
      { ...port("HDMI Out 2", "hdmi", "output", "hdmi"), notes: "Second camera stream, 1080p60 (dual-input codecs such as the SX80 integrator package)." },
      { ...port("Camera Control", "ethernet", "bidirectional", "rj45"), notes: "Point-to-point link to the codec's camera-control Ethernet port: control, speaker-track data and audio to the built-in speakers. Not on the LAN." },
      { ...port("Subwoofer Out", "analog-audio", "output", "rca"), notes: "Line-level RCA for an optional subwoofer; the bar's own speakers are internal (70 Hz-20 kHz, 90 dB SPL max)." },
      { ...port("USB-A", "usb", "bidirectional", "usb-a"), notes: "USB 2.0 Type-A." },
      { ...port("Maintenance", "usb", "bidirectional", "usb-micro"), notes: "Micro-USB maintenance port; factory-reset pinhole beside it." },
      { ...port("DC Power In", "power", "input", "barrel"), notes: "12 V DC from the supplied 100-240 V adapter (FSP FSP070-AHAN2 or AcBel ADF019, 5.83 A = 70 W rating). Power on/off button and Kensington slot on the same panel." },
    ],
  },
  {
    id: "b441e32b-1ff1-47fa-a1ec-23ca0e9666ac",
    deviceType: "speaker",
    label: "Biamp Desono C-IC6",
    shortName: "C-IC6",
    manufacturer: "Biamp",
    modelNumber: "Desono C-IC6",
    referenceUrl: "https://downloads.biamp.com/assets/docs/default-source/data-sheets/biamp_data_sheet_desono_c_ic6_aug23.pdf",
    searchTerms: ["desono", "c-ic6", "ceiling speaker", "conferencing loudspeaker", "biamp", "dwav"],
    widthMm: 276,
    heightMm: 151,
    depthMm: 276,
    weightKg: 3.5,
    voltage: "Passive, 8 ohm (60 W, 240 W peak)",
    unitCost: 276,
    dwavVerified: true,
    // Two-way 6.5 in coaxial conferencing ceiling loudspeaker: 60 Hz-20 kHz (-10 dB), 130 deg conical, 88 dB sensitivity, 112 dB peak SPL,
    // 8 ohm passive, 60 W continuous / 240 W peak. 151 mm deep x 276 mm dia, 248 mm cutout, 3.5 kg; C-ring, tile bridge and paintable grille
    // included; UL 2043 plenum. Euroblock (two parallel pairs) plus two RJ-45 for termination-free feeds from an AMP-450BP or TCM-XA.
    // Verified 2026-09-15 against Biamp data sheet aug23; CRM Products carries the same ports.
    ports: [
      { ...port("Speaker In (Euroblock)", "speaker-level", "input", "phoenix"), notes: "4-pole Euroblock, two parallel pairs, up to 16 AWG. 8 ohm passive, 60 W continuous (240 W peak)." },
      { ...port("Speaker In (RJ-45) 1", "speaker-level", "input", "rj45"), notes: "Termination-free speaker feed over category cable from a Tesira AMP-450BP or Parle TCM-XA." },
      { ...port("Speaker In (RJ-45) 2", "speaker-level", "passthrough", "rj45"), notes: "Parallel loop-through to the next C-IC6 on the same amplifier channel." },
    ],
  },
  {
    id: "4c83603a-5700-414f-b6a2-71683134491e",
    deviceType: "wired-mic",
    label: "Biamp Parl\u00e9 TCM-1",
    shortName: "TCM-1",
    manufacturer: "Biamp",
    modelNumber: "Parl\u00e9 TCM-1",
    referenceUrl: "https://downloads.biamp.com/assets/docs/default-source/data-sheets/biamp_data_sheet_parle_tcm-1_jul22.pdf",
    searchTerms: ["parle", "tcm-1", "pendant microphone", "beamtracking", "ceiling mic", "tesira", "biamp", "dwav"],
    widthMm: 63,
    heightMm: 51,
    depthMm: 63,
    weightKg: 0.2,
    powerDrawW: 15.4,
    voltage: "PoE IEEE 802.3at Class 3",
    unitCost: 2101,
    dwavVerified: true,
    // AVB Beamtracking pendant microphone for Tesira: pendant head 63 x 51 x 63 mm / 0.2 kg on a custom 2-pin lead (10 ft max drop) from a
    // plenum box 178 x 51 x 181 mm / 1.1 kg that carries the DSP, PoE (Class 3, 15.4 W) and a second RJ-45 for daisy-chaining up to two TCM-1EX.
    // Three 120 deg zones, 150 Hz-16 kHz, 106 dB max SPL. Verified 2026-09-15 against Biamp data sheet jul22.
    ports: [
      { ...port("Network (PoE)", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "AVB to the Tesira network from the plenum box. PoE IEEE 802.3at Class 3, 15.4 W." },
      { ...port("Daisy Chain Out", "ethernet", "output", "rj45"), notes: "To a TCM-1EX plenum box; max three mics per chain (one TCM-1 or TCM-1A plus two TCM-1EX)." },
    ],
  },
  {
    id: "8b46a786-ef1e-4fa9-9e67-cec99d60284b",
    deviceType: "wired-mic",
    label: "Biamp Parl\u00e9 TCM-XA",
    shortName: "TCM-XA",
    manufacturer: "Biamp",
    modelNumber: "Parl\u00e9 TCM-XA",
    referenceUrl: "https://downloads.biamp.com/assets/docs/default-source/data-sheets/biamp_data_sheet_parle-mics_all-models_jul22.pdf",
    searchTerms: ["parle", "tcm-xa", "tcm-x", "ceiling microphone", "beamtracking", "poe+ amplifier", "tesira", "biamp", "dwav"],
    widthMm: 150,
    heightMm: 17,
    depthMm: 150,
    weightKg: 0.34,
    powerDrawW: 30,
    voltage: "PoE+ IEEE 802.3at Class 4",
    unitCost: 3150,
    dwavVerified: true,
    // AVB Beamtracking ceiling microphone with a 2-channel PoE+ amplifier in its network box: mic head 150 mm dia x 17 mm / 0.34 kg on a 2 m
    // RJ-45 lead, network box 172 x 30 x 132 mm / 0.68 kg with DSP, PoE+ (Class 4, 30 W), an RJ-45 for a TCM-XEX (10 m max) and two RJ-45
    // speaker outputs (40 W @ 4 ohm / 30 W @ 8 ohm burst, 4 W continuous both driven). Four 90 deg zones, 109 dB max SPL.
    // Verified 2026-09-15 against Biamp Parle all-models data sheet jul22.
    ports: [
      { ...port("Network (PoE+)", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "AVB to the Tesira network; PoE+ IEEE 802.3at Class 4, 30 W; 100 m max to the switch." },
      { ...port("TCM-XEX Expansion", "ethernet", "output", "rj45"), notes: "Second mic (Parle TCM-XEX), proprietary digital + power, 10 m max." },
      { ...port("Speaker Out 1", "speaker-level", "output", "rj45"), notes: "Built-in Class D PoE+ amplifier: 40 W @ 4 ohm / 30 W @ 8 ohm burst, 8 W continuous one channel driven, 4 W both. Category cable to a Desono C-IC6." },
      { ...port("Speaker Out 2", "speaker-level", "output", "rj45"), notes: "Second amplifier channel, same rating; software-selectable power vs channel count." },
    ],
  },
  {
    id: "84cff4ca-fb37-47ae-a0e8-63ac605d1f30",
    deviceType: "wired-mic",
    label: "Biamp Parl\u00e9 TCM-XEX",
    shortName: "TCM-XEX",
    manufacturer: "Biamp",
    modelNumber: "Parl\u00e9 TCM-XEX",
    referenceUrl: "https://downloads.biamp.com/assets/docs/default-source/data-sheets/biamp_data_sheet_parle_tcm-xex_nov25.pdf",
    searchTerms: ["parle", "tcm-xex", "expansion microphone", "beamtracking", "ceiling mic", "tesira", "devio", "biamp", "dwav"],
    widthMm: 150,
    heightMm: 17,
    depthMm: 150,
    weightKg: 0.34,
    voltage: "From the host TCM-X / TCM-XA box",
    unitCost: 1635,
    dwavVerified: true,
    // Beamtracking expansion ceiling microphone: 150 mm dia x 17 mm / 0.34 kg, four 90 deg zones, 109 dB max SPL. In Tesira systems it hangs
    // off the spare RJ-45 of a TCM-X or TCM-XA network box (2 m captive lead, 10 m max) and cannot stand alone; in Devio it is a standalone mic.
    // Verified 2026-09-15 against Biamp data sheet nov25.
    ports: [
      { ...port("To TCM-X / TCM-XA Box", "ethernet", "input", "rj45"), notes: "Proprietary digital audio + power from the host network box; 2 m captive lead, 10 m max. Not standalone in Tesira systems." },
    ],
  },
  {
    id: "8cafc8bb-7bfc-41bc-9fb6-f980ff485484",
    deviceType: "amplifier",
    label: "Biamp Tesira AMP-450BP",
    shortName: "AMP-450BP",
    manufacturer: "Biamp",
    modelNumber: "Tesira AMP-450BP",
    referenceUrl: "https://downloads.biamp.com/assets/docs/default-source/data-sheets/biamp_data_sheet_tesira_amp-450bp.pdf",
    searchTerms: ["tesira", "amp-450bp", "poe+ amplifier", "backpack amplifier", "conferencing amplifier", "avb", "biamp", "dwav"],
    widthMm: 195,
    heightMm: 30,
    depthMm: 120,
    weightKg: 0.7,
    powerDrawW: 30,
    voltage: "PoE+ IEEE 802.3at Class 4",
    unitCost: 1028,
    dwavVerified: true,
    // Four-channel PoE+ conferencing amplifier, AVB endpoint: 195 x 30 x 120 mm, 0.7 kg, plenum rated (UL 2043), mounts to a Desono C-IC6 back
    // can (BPAK). Class D, 50 W @ 4 ohm / 30 W @ 8 ohm burst per channel; 15 W / 7 W / 3 W continuous with 1 / 2 / 4 channels driven;
    // software-selectable power vs channel count. RJ-45 speaker outputs for termination-free category-cable runs.
    // Verified 2026-09-15 against Biamp data sheet; CRM Products carries the same ports.
    ports: [
      { ...port("AVB Network (PoE+)", "ethernet", "bidirectional", "rj45"), addressable: true, notes: "Gigabit Ethernet; AVB audio and control from the Tesira system. PoE+ IEEE 802.3at Class 4, 30 W." },
      { ...port("Speaker Out 1", "speaker-level", "output", "rj45"), notes: "Class D; 50 W @ 4 ohm / 30 W @ 8 ohm burst; 15 W continuous one channel driven, 7 W two, 3 W all four. Category cable to a Desono C-IC6." },
      { ...port("Speaker Out 2", "speaker-level", "output", "rj45"), notes: "As channel 1." },
      { ...port("Speaker Out 3", "speaker-level", "output", "rj45"), notes: "As channel 1." },
      { ...port("Speaker Out 4", "speaker-level", "output", "rj45"), notes: "As channel 1." },
    ],
  },
];
